version: "3.5"

services:
  api01:
    hostname: api01
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "50MB"

  api02:
    hostname: api02
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "50MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

networks:
  default:
    driver: bridge
    name: rinha_backend_2024_q1
